name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ vars.GIST }}
          retries: 5
          retries_delay: 300
          config_output: svg
          output_condition: data-changed
          template: classic
          base: header, activity, community, repositories
          base_hireable: yes
          base_indepth: yes
          config_timezone: Asia/Singapore
          plugin_anilist: yes
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_shuffle: yes
          plugin_anilist_user: .user.login
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 40%
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: ${{ vars.STEAM_ID }}
          plugin_steam_achievements_limit: 2
          plugin_steam_games_ignored: 1172470
          plugin_steam_sections: player, most-played, recently-played

